package materialize

import (
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/autom8y/knossos/internal/fileutil"
	"github.com/autom8y/knossos/internal/paths"
	"github.com/autom8y/knossos/internal/provenance"
)

// Root .gitignore managed region markers, adapted from inscription marker convention.
const (
	rootGitignoreStartMarker = "# KNOSSOS:START channel-ignores"
	rootGitignoreEndMarker   = "# KNOSSOS:END channel-ignores"
)

// gitignoreHeader is the comment block at the top of generated channel .gitignore files.
const gitignoreHeader = `# Auto-generated by knossos sync from provenance manifest.
# DO NOT EDIT — regenerated on every sync.
# User-owned files are absent and visible to git.
`

// generateChannelGitignore creates or updates .gitignore inside the channel directory
// listing all owner:knossos entries from the provenance manifest. User-owned files
// are absent and thus visible to git.
//
// The generated file includes a self-entry so it does not appear in git status,
// making the mechanism purely local. Each developer gets the correct gitignore
// for their active rite after running ari sync.
//
// Returns true if a write occurred, false if content was identical or no knossos
// entries exist. Non-fatal: callers should log warnings on error, not abort the pipeline.
func generateChannelGitignore(channelDir string, manifest *provenance.ProvenanceManifest) (bool, error) {
	if manifest == nil || len(manifest.Entries) == 0 {
		return false, nil
	}

	// Collect knossos-owned paths, filtering outliers and inscription.
	var paths []string
	for path, entry := range manifest.Entries {
		if entry.Owner != provenance.OwnerKnossos {
			continue
		}
		if shouldExcludeFromGitignore(path) {
			continue
		}
		paths = append(paths, path)
	}

	// No knossos entries after filtering — nothing to ignore.
	if len(paths) == 0 {
		return false, nil
	}

	// Sort for deterministic output (required for WriteIfChanged idempotency).
	sort.Strings(paths)

	// Build gitignore content.
	var b strings.Builder
	b.WriteString(gitignoreHeader)
	b.WriteByte('\n')

	// Self-entry: the .gitignore file ignores itself (purely local mechanism).
	b.WriteString(".gitignore\n")

	for _, p := range paths {
		// Prefix with / to anchor to the channel dir root. Directory entries
		// already end with / in provenance (e.g. "commands/commit/").
		b.WriteByte('/')
		b.WriteString(p)
		b.WriteByte('\n')
	}

	gitignorePath := filepath.Join(channelDir, ".gitignore")
	return fileutil.WriteIfChanged(gitignorePath, []byte(b.String()), 0644)
}

// untrackKnossosFiles removes knossos-owned files from the git index so that
// the generated channel .gitignore takes effect for previously-tracked files.
// Git only ignores untracked files; already-tracked files show in git status
// regardless of .gitignore entries. This function bridges that gap by running
// git rm --cached on knossos-owned tracked files (files remain on disk).
//
// Best-effort: returns the count of files untracked. Silently returns 0 if
// git is unavailable, this is not a git repo, or no tracked files need removal.
func untrackKnossosFiles(projectRoot, channelDir string, manifest *provenance.ProvenanceManifest) int {
	if manifest == nil || len(manifest.Entries) == 0 {
		return 0
	}

	// Compute channel prefix relative to project root (e.g., ".channel/")
	relChannel, err := filepath.Rel(projectRoot, channelDir)
	if err != nil {
		return 0
	}
	channelPrefix := relChannel + "/"

	// List tracked files under the channel directory.
	// Fails silently if git is not installed or this is not a git repo.
	cmd := exec.Command("git", "-C", projectRoot, "ls-files", relChannel)
	output, err := cmd.Output()
	if err != nil || len(output) == 0 {
		return 0
	}

	tracked := make(map[string]bool)
	for _, line := range strings.Split(strings.TrimSpace(string(output)), "\n") {
		if line != "" {
			tracked[line] = true
		}
	}

	// Collect knossos-owned tracked files to untrack.
	var toUntrack []string
	for path, entry := range manifest.Entries {
		if entry.Owner != provenance.OwnerKnossos || shouldExcludeFromGitignore(path) {
			continue
		}

		if strings.HasSuffix(path, "/") {
			// Directory entry — find all tracked files under it.
			prefix := channelPrefix + path
			for tp := range tracked {
				if strings.HasPrefix(tp, prefix) {
					toUntrack = append(toUntrack, tp)
				}
			}
		} else {
			if gitPath := channelPrefix + path; tracked[gitPath] {
				toUntrack = append(toUntrack, gitPath)
			}
		}
	}

	if len(toUntrack) == 0 {
		return 0
	}

	sort.Strings(toUntrack)

	// Untrack via git rm --cached (files remain on disk).
	args := append([]string{"-C", projectRoot, "rm", "--cached", "--quiet", "--"}, toUntrack...)
	if err := exec.Command("git", args...).Run(); err != nil {
		slog.Warn("failed to untrack knossos-owned files", "channel", relChannel, "count", len(toUntrack), "error", err)
		return 0
	}

	slog.Info("untracked knossos-owned files from git index", "channel", relChannel, "count", len(toUntrack))
	return len(toUntrack)
}

// shouldExcludeFromGitignore returns true for provenance entries that must not
// appear in the channel .gitignore:
//
//   - ACTIVE_WORKFLOW.yaml — lives in .knossos/, not the channel dir
//   - .mcp.json — lives at project root, not the channel dir
//   - CLAUDE.md, GEMINI.md — inscription deferred as commitable
func shouldExcludeFromGitignore(path string) bool {
	switch path {
	case "ACTIVE_WORKFLOW.yaml":
		return true
	case ".mcp.json":
		return true
	case "CLAUDE.md", "GEMINI.md":
		return true
	default:
		return false
	}
}

// ensureRootGitignoreChannelEntries manages a KNOSSOS:START/END region in the
// project root .gitignore that lists all channel directories and root-level
// generated files (e.g., .mcp.json). This ensures that every channel directory
// is blanket-ignored at the root level, preventing tracked-file noise regardless
// of whether per-channel .gitignore files exist.
//
// The managed region uses inscription-style comment markers:
//
//	# KNOSSOS:START channel-ignores
//	.claude/
//	.gemini/
//	.mcp.json
//	# KNOSSOS:END channel-ignores
//
// If the region already exists, its contents are replaced. If absent, it is
// appended after any existing content. Entries outside the managed region are
// not touched — duplicate entries (e.g., a manual .claude/ line) are harmless.
//
// Non-fatal: callers should log warnings on error, not abort the pipeline.
func ensureRootGitignoreChannelEntries(projectRoot string) (bool, error) {
	gitignorePath := filepath.Join(projectRoot, ".gitignore")

	// Build the managed region content from all registered channels.
	channels := paths.AllChannels()
	var entries []string
	for _, ch := range channels {
		entries = append(entries, ch.DirName()+"/")
	}

	// Root-level generated files that live outside channel dirs.
	entries = append(entries, ".mcp.json")

	sort.Strings(entries)

	var region strings.Builder
	region.WriteString(rootGitignoreStartMarker)
	region.WriteString("\n")
	region.WriteString("# Auto-managed by ari sync — channel directories are regenerated on every sync.\n")
	region.WriteString("# Each channel also has a provenance-driven .gitignore for per-file precision.\n")
	for _, e := range entries {
		region.WriteString(e)
		region.WriteString("\n")
	}
	region.WriteString(rootGitignoreEndMarker)
	region.WriteString("\n")

	managedBlock := region.String()

	// Read existing .gitignore (may not exist yet).
	existing, err := os.ReadFile(gitignorePath)
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	content := string(existing)

	// Replace or append the managed region.
	startIdx := strings.Index(content, rootGitignoreStartMarker)
	endIdx := strings.Index(content, rootGitignoreEndMarker)

	var newContent string
	if startIdx >= 0 && endIdx > startIdx {
		// Replace existing region (include the end marker line + newline).
		endOfEndMarker := endIdx + len(rootGitignoreEndMarker)
		if endOfEndMarker < len(content) && content[endOfEndMarker] == '\n' {
			endOfEndMarker++
		}
		newContent = content[:startIdx] + managedBlock + content[endOfEndMarker:]
	} else {
		// Append: ensure trailing newline before the new block.
		if len(content) > 0 && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		if len(content) > 0 && !strings.HasSuffix(content, "\n\n") {
			content += "\n"
		}
		newContent = content + managedBlock
	}

	return fileutil.WriteIfChanged(gitignorePath, []byte(newContent), 0644)
}
