package materialize

import (
	"log/slog"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/autom8y/knossos/internal/fileutil"
	"github.com/autom8y/knossos/internal/provenance"
)

// gitignoreHeader is the comment block at the top of generated channel .gitignore files.
const gitignoreHeader = `# Auto-generated by knossos sync from provenance manifest.
# DO NOT EDIT — regenerated on every sync.
# User-owned files are absent and visible to git.
`

// generateChannelGitignore creates or updates .gitignore inside the channel directory
// listing all owner:knossos entries from the provenance manifest. User-owned files
// are absent and thus visible to git.
//
// The generated file includes a self-entry so it does not appear in git status,
// making the mechanism purely local. Each developer gets the correct gitignore
// for their active rite after running ari sync.
//
// Returns true if a write occurred, false if content was identical or no knossos
// entries exist. Non-fatal: callers should log warnings on error, not abort the pipeline.
func generateChannelGitignore(channelDir string, manifest *provenance.ProvenanceManifest) (bool, error) {
	if manifest == nil || len(manifest.Entries) == 0 {
		return false, nil
	}

	// Collect knossos-owned paths, filtering outliers and inscription.
	var paths []string
	for path, entry := range manifest.Entries {
		if entry.Owner != provenance.OwnerKnossos {
			continue
		}
		if shouldExcludeFromGitignore(path) {
			continue
		}
		paths = append(paths, path)
	}

	// No knossos entries after filtering — nothing to ignore.
	if len(paths) == 0 {
		return false, nil
	}

	// Sort for deterministic output (required for WriteIfChanged idempotency).
	sort.Strings(paths)

	// Build gitignore content.
	var b strings.Builder
	b.WriteString(gitignoreHeader)
	b.WriteByte('\n')

	// Self-entry: the .gitignore file ignores itself (purely local mechanism).
	b.WriteString(".gitignore\n")

	for _, p := range paths {
		// Prefix with / to anchor to the channel dir root. Directory entries
		// already end with / in provenance (e.g. "commands/commit/").
		b.WriteByte('/')
		b.WriteString(p)
		b.WriteByte('\n')
	}

	gitignorePath := filepath.Join(channelDir, ".gitignore")
	return fileutil.WriteIfChanged(gitignorePath, []byte(b.String()), 0644)
}

// untrackKnossosFiles removes knossos-owned files from the git index so that
// the generated channel .gitignore takes effect for previously-tracked files.
// Git only ignores untracked files; already-tracked files show in git status
// regardless of .gitignore entries. This function bridges that gap by running
// git rm --cached on knossos-owned tracked files (files remain on disk).
//
// Best-effort: returns the count of files untracked. Silently returns 0 if
// git is unavailable, this is not a git repo, or no tracked files need removal.
func untrackKnossosFiles(projectRoot, channelDir string, manifest *provenance.ProvenanceManifest) int {
	if manifest == nil || len(manifest.Entries) == 0 {
		return 0
	}

	// Compute channel prefix relative to project root (e.g., ".channel/")
	relChannel, err := filepath.Rel(projectRoot, channelDir)
	if err != nil {
		return 0
	}
	channelPrefix := relChannel + "/"

	// List tracked files under the channel directory.
	// Fails silently if git is not installed or this is not a git repo.
	cmd := exec.Command("git", "-C", projectRoot, "ls-files", relChannel)
	output, err := cmd.Output()
	if err != nil || len(output) == 0 {
		return 0
	}

	tracked := make(map[string]bool)
	for _, line := range strings.Split(strings.TrimSpace(string(output)), "\n") {
		if line != "" {
			tracked[line] = true
		}
	}

	// Collect knossos-owned tracked files to untrack.
	var toUntrack []string
	for path, entry := range manifest.Entries {
		if entry.Owner != provenance.OwnerKnossos || shouldExcludeFromGitignore(path) {
			continue
		}

		if strings.HasSuffix(path, "/") {
			// Directory entry — find all tracked files under it.
			prefix := channelPrefix + path
			for tp := range tracked {
				if strings.HasPrefix(tp, prefix) {
					toUntrack = append(toUntrack, tp)
				}
			}
		} else {
			if gitPath := channelPrefix + path; tracked[gitPath] {
				toUntrack = append(toUntrack, gitPath)
			}
		}
	}

	if len(toUntrack) == 0 {
		return 0
	}

	sort.Strings(toUntrack)

	// Untrack via git rm --cached (files remain on disk).
	args := append([]string{"-C", projectRoot, "rm", "--cached", "--quiet", "--"}, toUntrack...)
	if err := exec.Command("git", args...).Run(); err != nil {
		slog.Warn("failed to untrack knossos-owned files", "channel", relChannel, "count", len(toUntrack), "error", err)
		return 0
	}

	slog.Info("untracked knossos-owned files from git index", "channel", relChannel, "count", len(toUntrack))
	return len(toUntrack)
}

// shouldExcludeFromGitignore returns true for provenance entries that must not
// appear in the channel .gitignore:
//
//   - ACTIVE_WORKFLOW.yaml — lives in .knossos/, not the channel dir
//   - .mcp.json — lives at project root, not the channel dir
//   - CLAUDE.md, GEMINI.md — inscription deferred as commitable
func shouldExcludeFromGitignore(path string) bool {
	switch path {
	case "ACTIVE_WORKFLOW.yaml":
		return true
	case ".mcp.json":
		return true
	case "CLAUDE.md", "GEMINI.md":
		return true
	default:
		return false
	}
}
