{{/* know section template */}}
{{/* Owner: knossos - Always synced from Knossos templates */}}
<!-- KNOSSOS:START know -->
## Codebase Knowledge

Persistent codebase knowledge is available in `.know/`. Generated by `/know --all`.

### Auto-load (read before any code modification)
- `Read(".know/architecture.md")` -- package structure, layers, entry points, data flow

### Load on demand (read when relevant to current task)
- `Read(".know/scar-tissue.md")` -- past bugs, regressions, defensive patterns from failures
- `Read(".know/design-constraints.md")` -- structural tensions, load-bearing decisions, frozen areas

### Task-specific (read when writing code or tests)
- `Read(".know/conventions.md")` -- error handling style, file organization, domain idioms
- `Read(".know/test-coverage.md")` -- test gaps, coverage patterns, testing conventions

Check freshness: `ari knows`. Regenerate: `/know [domain]` or `/know --all`.
<!-- KNOSSOS:END know -->
