// Package know provides shared parsing for .know/ codebase knowledge files.
// Knowledge files are markdown with YAML frontmatter describing pre-computed
// codebase context generated by theoros.
package know

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/autom8y/knossos/internal/frontmatter"
)

// gitDiffNameOnly is the function used to get changed files between two commits.
// Replaceable in tests to avoid real git invocations.
var gitDiffNameOnly = defaultGitDiffNameOnly

func defaultGitDiffNameOnly(fromHash, toHash string) ([]string, error) {
	out, err := exec.Command("git", "diff", "--name-only", fromHash+".."+toHash).Output()
	if err != nil {
		return nil, err
	}
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	if len(lines) == 1 && lines[0] == "" {
		return nil, nil
	}
	return lines, nil
}

// Meta holds the frontmatter of a .know/ domain file.
type Meta struct {
	Domain        string   `yaml:"domain"`
	GeneratedAt   string   `yaml:"generated_at"`
	ExpiresAfter  string   `yaml:"expires_after"`
	SourceScope   []string `yaml:"source_scope"`
	Generator     string   `yaml:"generator"`
	SourceHash    string   `yaml:"source_hash"`
	Confidence    float64  `yaml:"confidence"`
	FormatVersion string   `yaml:"format_version"`
	// Incremental update tracking
	UpdateMode           string `yaml:"update_mode,omitempty"`
	IncrementalCycle     int    `yaml:"incremental_cycle,omitempty"`
	MaxIncrementalCycles int    `yaml:"max_incremental_cycles,omitempty"`
}

// DomainStatus reports freshness for a single .know/ domain.
type DomainStatus struct {
	Domain      string  `json:"domain"`
	Generated   string  `json:"generated_at"`
	Expires     string  `json:"expires_at"`
	Fresh       bool    `json:"fresh"`
	TimeExpired bool    `json:"time_expired"`
	SourceHash  string  `json:"source_hash"`
	CurrentHash string  `json:"current_hash"`
	CodeChanged bool    `json:"code_changed"`
	Confidence  float64 `json:"confidence"`
	ForceFull   bool    `json:"force_full"`
}

// ReadMeta reads and parses all .know/*.md files in knowDir, and also scans
// .know/feat/*.md (one level deep). Missing directory returns an empty slice
// (not an error). Files with unparseable frontmatter are skipped with a warning
// logged to stderr.
func ReadMeta(knowDir string) ([]DomainStatus, error) {
	entries, err := os.ReadDir(knowDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read .know/ directory: %w", err)
	}

	now := time.Now().UTC()

	// Resolve current git HEAD hash once for all domains in this call.
	// An empty string means git is unavailable; code-changed check is skipped.
	currentHash := resolveGitHead()

	var results []DomainStatus

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}

		path := filepath.Join(knowDir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warn: cannot read %s: %v\n", path, err)
			continue
		}

		yamlBytes, _, err := frontmatter.Parse(data)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warn: no frontmatter in %s: %v\n", path, err)
			continue
		}

		var meta Meta
		if err := yaml.Unmarshal(yamlBytes, &meta); err != nil {
			fmt.Fprintf(os.Stderr, "warn: malformed frontmatter in %s: %v\n", path, err)
			continue
		}

		if meta.Domain == "" {
			// Use filename stem as fallback domain name
			meta.Domain = strings.TrimSuffix(entry.Name(), ".md")
		}

		status := buildDomainStatus(meta, now, currentHash)
		results = append(results, status)
	}

	// Scan .know/feat/*.md (one level deep only).
	// Domain names are prefixed as "feat/{slug}" (e.g., "feat/materialization").
	featDir := filepath.Join(knowDir, "feat")
	featEntries, err := os.ReadDir(featDir)
	if err != nil {
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("read .know/feat/ directory: %w", err)
		}
		// feat/ doesn't exist: not an error, just no feature domains. Continue to release/.
	} else {
		for _, entry := range featEntries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
				continue
			}

			path := filepath.Join(featDir, entry.Name())
			data, err := os.ReadFile(path)
			if err != nil {
				fmt.Fprintf(os.Stderr, "warn: cannot read %s: %v\n", path, err)
				continue
			}

			yamlBytes, _, err := frontmatter.Parse(data)
			if err != nil {
				fmt.Fprintf(os.Stderr, "warn: no frontmatter in %s: %v\n", path, err)
				continue
			}

			var meta Meta
			if err := yaml.Unmarshal(yamlBytes, &meta); err != nil {
				fmt.Fprintf(os.Stderr, "warn: malformed frontmatter in %s: %v\n", path, err)
				continue
			}

			// Always use "feat/{slug}" as the domain name regardless of frontmatter domain field.
			// This ensures consistent namespacing and prevents collisions with top-level domains.
			slug := strings.TrimSuffix(entry.Name(), ".md")
			meta.Domain = "feat/" + slug

			status := buildDomainStatus(meta, now, currentHash)
			results = append(results, status)
		}
	}

	// Scan .know/release/*.md (one level deep only).
	// Domain names are prefixed as "release/{slug}" (e.g., "release/platform-profile").
	releaseDir := filepath.Join(knowDir, "release")
	releaseEntries, err := os.ReadDir(releaseDir)
	if err != nil {
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("read .know/release/ directory: %w", err)
		}
		// release/ doesn't exist: not an error.
		return results, nil
	}

	for _, entry := range releaseEntries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}

		path := filepath.Join(releaseDir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warn: cannot read %s: %v\n", path, err)
			continue
		}

		yamlBytes, _, err := frontmatter.Parse(data)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warn: no frontmatter in %s: %v\n", path, err)
			continue
		}

		var meta Meta
		if err := yaml.Unmarshal(yamlBytes, &meta); err != nil {
			fmt.Fprintf(os.Stderr, "warn: malformed frontmatter in %s: %v\n", path, err)
			continue
		}

		slug := strings.TrimSuffix(entry.Name(), ".md")
		meta.Domain = "release/" + slug

		status := buildDomainStatus(meta, now, currentHash)
		results = append(results, status)
	}

	return results, nil
}

// resolveGitHead returns the short git SHA of HEAD in the current working directory.
// Returns an empty string if git is unavailable or the directory is not a git repo.
func resolveGitHead() string {
	out, err := exec.Command("git", "rev-parse", "--short", "HEAD").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

// scopedStaleness checks whether any files matching sourceScope globs changed
// between sourceHash and currentHash. Returns true if in-scope files changed.
// Returns false (not stale) if git is unavailable, either hash is empty,
// or sourceScope is empty (caller falls back to hash comparison).
func scopedStaleness(sourceHash, currentHash string, sourceScope []string) bool {
	if len(sourceScope) == 0 || sourceHash == "" || currentHash == "" {
		return false
	}

	changedFiles, err := gitDiffNameOnly(sourceHash, currentHash)
	if err != nil {
		// git unavailable or error: assume not stale (graceful degradation).
		return false
	}

	for _, changedFile := range changedFiles {
		if changedFile == "" {
			continue
		}
		for _, glob := range sourceScope {
			if matchScope(glob, changedFile) {
				return true
			}
		}
	}

	return false
}

// matchScope returns true if path matches the scope glob pattern.
// Handles ** as "any number of path segments". Strips leading "./" from pattern.
// This handles the two patterns actually used in source_scope without external deps:
//   - "internal/**/*.go" -> prefix match on "internal/" + suffix match on ".go"
//   - "cmd/**/*.go"      -> prefix match on "cmd/" + suffix match on ".go"
//   - "go.mod"           -> exact or filepath.Match
func matchScope(pattern, path string) bool {
	// Normalize: strip leading "./" from source_scope values.
	pattern = strings.TrimPrefix(pattern, "./")

	if !strings.Contains(pattern, "**") {
		// No double-star: use filepath.Match for standard glob handling.
		matched, err := filepath.Match(pattern, path)
		if err != nil {
			return false
		}
		return matched
	}

	// Split on "**" to get the prefix and suffix portions.
	// Pattern like "internal/**/*.go" splits into ["internal/", "/*.go"].
	parts := strings.SplitN(pattern, "**", 2)
	prefix := parts[0] // e.g., "internal/"
	suffix := parts[1] // e.g., "/*.go"

	// Check prefix match: path must start with the prefix (if non-empty).
	if prefix != "" && !strings.HasPrefix(path, prefix) {
		return false
	}

	if suffix == "" {
		// Pattern like "internal/**": matches anything under the prefix.
		return true
	}

	// Strip leading "/" from suffix to get the trailing pattern.
	// e.g., "/*.go" -> "*.go"
	suffixPattern := strings.TrimPrefix(suffix, "/")
	if suffixPattern == "" {
		return true
	}

	// The remaining path (after the prefix) must match the suffix pattern.
	remaining := strings.TrimPrefix(path, prefix)
	// Use filepath.Match on the base name component for simple suffix patterns.
	// For "*.go", we want to match any .go file at any depth under prefix.
	// Check if the last segment matches the suffix pattern.
	base := filepath.Base(remaining)
	matched, err := filepath.Match(suffixPattern, base)
	if err != nil {
		return false
	}
	return matched
}

// buildDomainStatus computes freshness for a single domain.
// currentHash is the current git HEAD short SHA; empty means unavailable.
func buildDomainStatus(meta Meta, now time.Time, currentHash string) DomainStatus {
	status := DomainStatus{
		Domain:      meta.Domain,
		Generated:   meta.GeneratedAt,
		SourceHash:  meta.SourceHash,
		CurrentHash: currentHash,
		Confidence:  meta.Confidence,
		Fresh:       true, // default: assume fresh if unparseable
	}

	// Parse generation time
	generatedAt, err := time.Parse(time.RFC3339, meta.GeneratedAt)
	if err != nil {
		// Unparseable timestamp: treat as stale to be safe
		status.Fresh = false
		status.TimeExpired = true
		status.Expires = "unknown"
		return status
	}

	// Parse expires_after duration
	expiresAfter, err := ParseDuration(meta.ExpiresAfter)
	if err != nil {
		// Unparseable duration: treat as stale to be safe
		status.Fresh = false
		status.TimeExpired = true
		status.Expires = "unknown"
		return status
	}

	expiresAt := generatedAt.Add(expiresAfter)
	status.Expires = expiresAt.UTC().Format("2006-01-02")

	// Time-based staleness
	timeExpired := !now.Before(expiresAt)

	// Code-based staleness: compares source_hash against HEAD.
	// Skip when either value is unavailable (empty string).
	// When source_scope is set and hashes differ, use scoped staleness to check
	// whether any in-scope files actually changed — avoiding false staleness
	// from commits that only touched docs or other out-of-scope files.
	var codeChanged bool
	if currentHash != "" && meta.SourceHash != "" {
		if currentHash == meta.SourceHash {
			codeChanged = false // identical hash, definitely fresh
		} else if len(meta.SourceScope) > 0 {
			codeChanged = scopedStaleness(meta.SourceHash, currentHash, meta.SourceScope)
		} else {
			codeChanged = true // no scope defined, fall back to hash inequality
		}
	}

	status.TimeExpired = timeExpired
	status.CodeChanged = codeChanged
	status.Fresh = !timeExpired && !codeChanged

	// If we've hit the maximum incremental cycles, force a full regeneration
	// on the next update regardless of delta size.
	// MaxIncrementalCycles == 0 means "no limit" (backward compat with existing files).
	if meta.MaxIncrementalCycles > 0 && meta.IncrementalCycle >= meta.MaxIncrementalCycles {
		status.ForceFull = true
	}

	return status
}

// ReadSingleMeta reads and parses the frontmatter of a single .know/ domain file.
// domain may be a plain name ("architecture") or a feat namespace ("feat/materialization").
// Returns the parsed Meta or an error if the file doesn't exist or is unparseable.
func ReadSingleMeta(knowDir, domain string) (*Meta, error) {
	path := DomainFilePath(knowDir, domain)
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read domain %q: %w", domain, err)
	}
	yamlBytes, _, err := frontmatter.Parse(data)
	if err != nil {
		return nil, fmt.Errorf("parse frontmatter for %q: %w", domain, err)
	}
	var meta Meta
	if err := yaml.Unmarshal(yamlBytes, &meta); err != nil {
		return nil, fmt.Errorf("unmarshal frontmatter for %q: %w", domain, err)
	}
	if meta.Domain == "" {
		meta.Domain = domain
	}
	return &meta, nil
}

// ParseDuration parses a duration string supporting "d" for days in addition to
// standard Go duration units (h, m, s). Examples: "7d", "14d", "2h", "30m".
func ParseDuration(s string) (time.Duration, error) {
	if s == "" {
		return 0, fmt.Errorf("empty duration string")
	}

	// Handle "Nd" form (days)
	if strings.HasSuffix(s, "d") {
		dayStr := s[:len(s)-1]
		days, err := strconv.Atoi(dayStr)
		if err != nil {
			return 0, fmt.Errorf("invalid day count %q in duration %q", dayStr, s)
		}
		if days < 0 {
			return 0, fmt.Errorf("negative day count in duration %q", s)
		}
		return time.Duration(days) * 24 * time.Hour, nil
	}

	// Delegate everything else to standard library
	return time.ParseDuration(s)
}
