// Package know provides shared parsing for .know/ codebase knowledge files.
// Knowledge files are markdown with YAML frontmatter describing pre-computed
// codebase context generated by theoros.
package know

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/autom8y/knossos/internal/frontmatter"
)

// Meta holds the frontmatter of a .know/ domain file.
type Meta struct {
	Domain        string   `yaml:"domain"`
	GeneratedAt   string   `yaml:"generated_at"`
	ExpiresAfter  string   `yaml:"expires_after"`
	SourceScope   []string `yaml:"source_scope"`
	Generator     string   `yaml:"generator"`
	SourceHash    string   `yaml:"source_hash"`
	Confidence    float64  `yaml:"confidence"`
	FormatVersion string   `yaml:"format_version"`
}

// DomainStatus reports freshness for a single .know/ domain.
type DomainStatus struct {
	Domain      string  `json:"domain"`
	Generated   string  `json:"generated_at"`
	Expires     string  `json:"expires_at"`
	Fresh       bool    `json:"fresh"`
	TimeExpired bool    `json:"time_expired"`
	SourceHash  string  `json:"source_hash"`
	CurrentHash string  `json:"current_hash"`
	CodeChanged bool    `json:"code_changed"`
	Confidence  float64 `json:"confidence"`
}

// ReadMeta reads and parses all .know/*.md files in knowDir.
// Missing directory returns an empty slice (not an error).
// Files with unparseable frontmatter are skipped with a warning logged to stderr.
func ReadMeta(knowDir string) ([]DomainStatus, error) {
	entries, err := os.ReadDir(knowDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read .know/ directory: %w", err)
	}

	now := time.Now().UTC()

	// Resolve current git HEAD hash once for all domains in this call.
	// An empty string means git is unavailable; code-changed check is skipped.
	currentHash := resolveGitHead()

	var results []DomainStatus

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}

		path := filepath.Join(knowDir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warn: cannot read %s: %v\n", path, err)
			continue
		}

		yamlBytes, _, err := frontmatter.Parse(data)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warn: no frontmatter in %s: %v\n", path, err)
			continue
		}

		var meta Meta
		if err := yaml.Unmarshal(yamlBytes, &meta); err != nil {
			fmt.Fprintf(os.Stderr, "warn: malformed frontmatter in %s: %v\n", path, err)
			continue
		}

		if meta.Domain == "" {
			// Use filename stem as fallback domain name
			meta.Domain = strings.TrimSuffix(entry.Name(), ".md")
		}

		status := buildDomainStatus(meta, now, currentHash)
		results = append(results, status)
	}

	return results, nil
}

// resolveGitHead returns the short git SHA of HEAD in the current working directory.
// Returns an empty string if git is unavailable or the directory is not a git repo.
func resolveGitHead() string {
	out, err := exec.Command("git", "rev-parse", "--short", "HEAD").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

// buildDomainStatus computes freshness for a single domain.
// currentHash is the current git HEAD short SHA; empty means unavailable.
func buildDomainStatus(meta Meta, now time.Time, currentHash string) DomainStatus {
	status := DomainStatus{
		Domain:      meta.Domain,
		Generated:   meta.GeneratedAt,
		SourceHash:  meta.SourceHash,
		CurrentHash: currentHash,
		Confidence:  meta.Confidence,
		Fresh:       true, // default: assume fresh if unparseable
	}

	// Parse generation time
	generatedAt, err := time.Parse(time.RFC3339, meta.GeneratedAt)
	if err != nil {
		// Unparseable timestamp: treat as stale to be safe
		status.Fresh = false
		status.TimeExpired = true
		status.Expires = "unknown"
		return status
	}

	// Parse expires_after duration
	expiresAfter, err := ParseDuration(meta.ExpiresAfter)
	if err != nil {
		// Unparseable duration: treat as stale to be safe
		status.Fresh = false
		status.TimeExpired = true
		status.Expires = "unknown"
		return status
	}

	expiresAt := generatedAt.Add(expiresAfter)
	status.Expires = expiresAt.UTC().Format("2006-01-02")

	// Time-based staleness
	timeExpired := !now.Before(expiresAt)

	// Code-based staleness: stale when source_hash differs from HEAD.
	// Skip this check when either value is unavailable (empty string).
	var codeChanged bool
	if currentHash != "" && meta.SourceHash != "" {
		codeChanged = meta.SourceHash != currentHash
	}

	status.TimeExpired = timeExpired
	status.CodeChanged = codeChanged
	status.Fresh = !timeExpired && !codeChanged

	return status
}

// ParseDuration parses a duration string supporting "d" for days in addition to
// standard Go duration units (h, m, s). Examples: "7d", "14d", "2h", "30m".
func ParseDuration(s string) (time.Duration, error) {
	if s == "" {
		return 0, fmt.Errorf("empty duration string")
	}

	// Handle "Nd" form (days)
	if strings.HasSuffix(s, "d") {
		dayStr := s[:len(s)-1]
		days, err := strconv.Atoi(dayStr)
		if err != nil {
			return 0, fmt.Errorf("invalid day count %q in duration %q", dayStr, s)
		}
		if days < 0 {
			return 0, fmt.Errorf("negative day count in duration %q", s)
		}
		return time.Duration(days) * 24 * time.Hour, nil
	}

	// Delegate everything else to standard library
	return time.ParseDuration(s)
}
